### ISSUE TITLE
Date is a bit off the screen

### ISSUE THREAD

**Issue by Zehra** [allejo/roconut#4]
I'm not sure if this helps, but I'm using FireFox on Windows 10.

**Screenshot taken at 50% according to FireFox.**
![1 error at 50 screensize](https://user-images.githubusercontent.com/22282963/35492011-2a8595c2-0478-11e8-91a5-961711e229f7.png)
I'm able to see the dates, but they appear a bit off the main part of the screen.

**Screenshot taken at 67% according to FireFox.**
![1 error at 67 screensize](https://user-images.githubusercontent.com/22282963/35492047-5a11466a-0478-11e8-8d13-1a439b0a6d97.png)
I'm able to see the dates, but need to scroll a bit.

**Screenshot taken at 90% according to FireFox.**
![1 error at 90 screensize](https://user-images.githubusercontent.com/22282963/35492063-82abbbfa-0478-11e8-8e4f-21d7291f033a.png)
It's pretty visible and some movement is needed.

**Screenshot taken at 100% according to FireFox.**
![1 error at 100 screensize](https://user-images.githubusercontent.com/22282963/35492084-a7b4cfe0-0478-11e8-8c30-0e20c19f6b29.png)
I didn't notice the dates were there, until I was about to suggest it as a feature.

-Zehra

**Comment by allejo** [comment]
Is this because one of your paste names really long?

**Comment by allejo** [comment]
Should be fixed in master, not pushed to production yet. That'll happen this week
